### ISSUE TITLE
vls v0.0.62 seems to be broken

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-vue#10]
With vls updated to v0.0.62 (LSP-vue v0.0.10), I don't seem to get any errors reported in Vue files and hover popups don't show up when hovering variables/functions/anything.

**Comment by rchl** [comment]
Probably this issue https://github.com/vuejs/vetur/issues/1449

**Comment by predragnikolic** [comment]
I downgraded the server to 0.0.61 and made a release
until vuejs/vetur#1449 gets fixed

The hover and diagnostics only works in the template section, and the completion works only for snippets.

**Comment by predragnikolic** [comment]
0.0.63 is out with a fix for vuejs/vetur#1449.

**Comment by rchl** [comment]
People seem to be reporting that the are still problems though.

**Comment by predragnikolic** [comment]
Yes, I was about to write the exact same thing,
So I don't know if I should make a release to package control, until that gets fixed.

**Comment by predragnikolic** [comment]
I would like to wait for this to be completely fixed before making a new release :)

**Comment by predragnikolic** [comment]
closed with #13
