### ISSUE TITLE
modules import references

### ISSUE THREAD

**Issue by xinxilas** [sublimelsp/LSP-vue#106]
Its an bug or are there any configs i must setup to be able to access path references on .vue files?

Sorry if i must config something i did not

relative paths and '@' paths not working

PS: i have jsconfig.json i used o vscode, and it is ok there
```
{
	"compilerOptions": {
	  "baseUrl": ".",
	  "paths": {
		 "@/*": ["./src/*"]
	  }
	},
	"include": [
		"./src/**/*.js",
		"./src/**/*.vue"
	],
	"exclude": ["node_modules", "dist"]
 }
```
 

![image](https://user-images.githubusercontent.com/38674705/124298818-16f67e00-db33-11eb-975e-2af12e6b99a2.png)

**Comment by rchl** [comment]
have you tried importing with the `.vue` extension included?

**Comment by rchl** [comment]
BTW. Are you talking about `Go to definition` feature or are you getting an error in the document with that code.

**Comment by xinxilas** [comment]
yes, "Go to definition", it worked using *.vue
Ill use .vue now...

But if is there any solution or already known file to setup .vue as one of the common imported files would be nice
Or maybe it isn't lsp-typescript or lsp-vue issue?

Thank you

**Comment by rchl** [comment]
I'll close this since there is nothing this package can do about it.
You can file a bug at https://github.com/vuejs/vetur/ if you care although I don't have high hopes that anyone would care about that issue.
