### ISSUE TITLE
[Feature Required] support settings in sublime-project file

### ISSUE THREAD

**Issue by halfmoonvic** [sublimelsp/LSP-vue#115]
I want to use lsp-vue in the vue2 project, and use lsp-volar in the vue3 project. 
the "enabled" option can be set in the xxx.sublime-project will be nice, like below
```
"settings": {
	"lsp_vue": {
		"enabled": true
	},
	"lsp_volar": {
		"enabled": false
	},
}
```

**Comment by rchl** [comment]
```js
	"settings":
	{
		"LSP":
		{
			"LSP-vue": {
				"enabled": true,
			},
			"LSP-volar":
			{
				"enabled": false,
			},
		},
	},
```

Optionally install `LSP-json` to get autocompletion and validation in settings.

**Comment by rwols** [comment]
See also https://lsp.sublimetext.io/guides/client_configuration/#per-project-overrides
