### ISSUE TITLE
vue 3 volar support ?

### ISSUE THREAD

**Issue by productdevbook** [sublimelsp/LSP-vue#117]

**Comment by rwols** [comment]
See https://github.com/sublimelsp/LSP-volar

**Comment by rchl** [comment]
It supports Vue 3 but I guess you mean the `<script setup>` which has its own issue.

Since we rely on vetur here, we just have to wait until it's implemented there. Nothing we can do here.

**Comment by rchl** [comment]
I really want to rename this to `LSP-vetur` now :)
