### ISSUE TITLE
LSP server doesn't load with fresh install

### ISSUE THREAD

**Issue by rrrrando** [sublimelsp/LSP-vue#14]
Looks like the the problem is in the sublime config file. When the default settings are commented out then LSP can't load LSP-vue server. When i uncommented the settings file, the server started working again. I can create a pull request if needed, but it's a very fast fix.

https://github.com/sublimelsp/LSP-vue/blob/8610b91b0f80399bf87cfc16f25d1ce076e65f46/LSP-vue.sublime-settings#L12-L48

**Comment by predragnikolic** [comment]
Thanks for reporting. 
Vue language server although a really great language server, is a pain when it comes to passing initialization options, and will fail if something is missing. :D

**Comment by rrrrando** [comment]
Thanks! Happy to help!
