### ISSUE TITLE
Disable autocomplete for specific languages in .vue files

### ISSUE THREAD

**Issue by Jax0rz** [sublimelsp/LSP-vue#16]
Autocomplete is useful for JS so I want it. I don't need it for CSS because [CSS3](https://packagecontrol.io/packages/CSS3)'s autocomplete is better.When using the default css syntax or [CSS3](https://packagecontrol.io/packages/CSS3),there will show duplicate autocompletion

<img width="413" alt="Xnip2020-01-24_17-15-40" src="https://user-images.githubusercontent.com/7557357/73057844-6a3fb800-3ecd-11ea-9651-e266cb8f773c.png">
 
so how to disable css auto completion in lsp-vue,such as:

<img width="307" alt="Xnip2020-01-24_17-19-51" src="https://user-images.githubusercontent.com/7557357/73058063-c9053180-3ecd-11ea-8ca8-50f14a377ab7.png">

**Comment by predragnikolic** [comment]
Did you found a way or you just closed it?

**Comment by Jax0rz** [comment]
> Did you found a way or you just closed it?

No,I don't found a way

**Comment by rchl** [comment]
Maybe try:
```js
"css": {
  "completion": {
    "triggerPropertyValueCompletion": false,
    "completePropertyWithSemicolon": false,
  }
}
```
That's from quick look at their code.

**Comment by Jax0rz** [comment]
> Maybe try:
> 
> ```js
> "css": {
>   "completion": {
>     "triggerPropertyValueCompletion": false,
>     "completePropertyWithSemicolon": false,
>   }
> }
> ```
> 
> That's from quick look at their code.

Wow,Thanks,it works perfectly.
