### ISSUE TITLE
Error during start of LS

### ISSUE THREAD

**Issue by nick79** [sublimelsp/LSP-vue#20]
OS: Linux (Ubuntu / Pop OS)

Text Editor: Sublime Text 3, Version 3.2.2, Build 3211

**Problem** 

LS do not start properly. In bottom left corner there is shown following message: "Please install Node js for the Vue language server to work". Also here is log:

`LSP-vue: Installing server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/nik/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 21, in run_in_thread
    subprocess.check_call(popen_args, shell=sublime.platform() == 'windows')
  File "./python3.3/subprocess.py", line 542, in check_call
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

Package Control: Skipping automatic upgrade, last run at 2020-03-29 11:36:51, next run at 2020-03-29 12:36:51 or after
Unable to open /home/nik/.config/sublime-text-3/Packages/LSP-vue/LSP-vue.sublime-settings`

Here the main problem is that I already have installed Node js using   [.asdf](https://github.com/asdf-vm/asdf). Here is output of testing installed versions:
`➜  ~ node --version
v12.13.1
➜  ~ npm --version 
6.13.7
`

It looks like that Sublime/LSP-vue somehow is not aware of node and npm installed versions using .asdf.

Thanks in advance,
Milan

**Comment by rchl** [comment]
You need to make node visible on the PATH like asdf says here https://asdf-vm.com/#/core-manage-asdf-vm?id=add-to-your-shell although you might need to put that code in `.bash_profile`, `.profile` or `.zprofile`, depending on your situation. Remember to re-login to your OS after changing those.

**Comment by nick79** [comment]
As I already said - node is on path and if I execute for example in terminal:
`node --version`
I get output: `v12.13.1`

**Comment by rwols** [comment]
But does SublimeText pick it up? Run the following in the SublimeText console:

```
>>> import os; os.environ["PATH"]
'/home/raoul/Downloads/1.1.126.0/x86_64/bin:/home/raoul/.local/bin:/snap/bin:/usr/local/go/bin:/home/raoul/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
```

**Comment by rchl** [comment]
I'm not sure about Linux but on Mac it's not that simple. Even though you have it on the PATH in the terminal, ST, being a GUI app, doesn't inherit those. I wouldn't expect it to be the same on Linux but I'm not up to date with it so who knows.

**Comment by nick79** [comment]
@rwols I think that is the problem.

This is what I get from Sublime Text when I execute command you send to me:
`'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'`

And this is what I get, when from terminal I check PATH:
`PATH=/home/nik/.asdf/shims:/home/nik/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

You see, in terminal there is those two .asdf folders on path.

Do you have an idea how to "fix" this Sublime Text problem :)

**Comment by rwols** [comment]
Try creating a `.zprofile` and putting this in it:

```
if [ -f ~/.zshrc ]; then
    . ~/.zshrc
fi
```
then restart SublimeText and check the path again.

**Comment by predragnikolic** [comment]
If @rwols solution doesn't work.

Try adding the same $PATH to .bashrc or .profile. Log out and log in .

I think Sublime doesn't load the $PATH from .zshrc . Instead I think I load it from .bashrc or .profile. So try to export the $PATH in one if those files.

**Comment by rchl** [comment]
I've reproduced this problem with my virtualized Ubuntu.

My setup has `zsh` as the default shell (both for root and normal user).

ST only started seeing node path when I've added init script (in my case `. /home/rchlodnicki/.asdf/asdf.sh`) to `~/.profile` and re-logged/restarted. It didn't work with `.zprofile`.

Also, I wouldn't source the whole `.bashrc` or `.zshrc` from there, just put the `asdf` (or `nvm`) init script there.

We definitively should have that in some generic form in the readme of all LSP-* packages.

**Comment by rchl** [comment]
BTW. I think ST only sources that script manually on Mac.
On Linux it's the system doing the job of propagating env to GUI app.
I think so because ST doesn't print anything in the console about that on Linux, unlike on Mac.

**Comment by nick79** [comment]
Thanks you all. After trying everything that you suggest there are two solutions:
1. Simple and boring - open termina app, go to the folder of the project and run `subl .`
2. in `~.profile` file add `.asdf` ini script: `. $HOME/.asdf/asdf/sh`

Once more, thank you all for your help. I understand that this is Sublime Text 3 problem and not LSP-vue plugin per se. I will close this ticket.
