### ISSUE TITLE
Cannot read property 'tabSize` of undefined

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-vue#3]
When trying to use codeAction I get error in the status bar as in the subject.

Similar to #2 so propably missing that setting in configuration.

![vetur-tabsize-error](https://user-images.githubusercontent.com/153197/63619409-e2d4dc80-c5ee-11e9-9264-0077cabdcafe.png)

**Comment by rchl** [comment]
No error if I add that setting in vue-lsp configuration file.

ref: https://github.com/vuejs/vetur/blob/cf893ed856347a85701b4f887027769a28a0c313/server/src/config.ts#L12

But it would be ideal if this plugin could figure it out from view. Is that possible or not really since language server is initialized once per project?

**Comment by predragnikolic** [comment]
Thanks for reporting.

I avoided adding logic for determining the tabSize. 
I just added an empty `options` object, so the Vetur language server don't throw that error (https://github.com/sublimelsp/LSP-vue/commit/93bea87cb98e66edd557eeff6743f500d98aae00).

And now the code actions work.
<img width="794" alt="Screen Shot 2019-08-25 at 10 11 01 AM" src="https://user-images.githubusercontent.com/22029477/63647421-6f7fb780-c721-11e9-85fb-e7436f53130d.png">

But when I chose a code action, I now get `Unhandled method workspace/executeCommand`.
<img width="308" alt="Screen Shot 2019-08-25 at 10 10 51 AM" src="https://user-images.githubusercontent.com/22029477/63647425-81f9f100-c721-11e9-93ae-5ab9a502dc0e.png">

**Comment by rwols** [comment]
We could do something similar to this perhaps?

https://github.com/tomv564/LSP/blob/c2727cfe1d54604044fd024f378893c9d30a26a8/plugin/formatting.py#L15-L19

**Comment by rchl** [comment]
> But when I chose a code action, I now get Unhandled method `workspace/executeCommand`.

Same, didn't actually test that before.

> We could do something similar to this perhaps?

I think we should if possible as it's probably useful for some formatting features (just guessing, haven't looked at the code).

**Comment by predragnikolic** [comment]
LSP supports `workspace/executeCommand`. 
But I don't know the reason why I get `Unhandled method workspace/executeCommand`.

**Comment by predragnikolic** [comment]
What do you guys think of this?
I personally don't like this, but if you have a better solution, I am open for suggestions

```diff
   @property
    def config(self) -> ClientConfig:
        settings = sublime.load_settings("LSP-vue.sublime-settings")
+        config = settings.get('config')
+        view = sublime.active_window().active_view()
+        if view is not None:
+            config['vetur']['format']['options']['tabs_size'] = view.settings().get("tab_size", 4)
+            config['vetur']['format']['options']['useTabs'] = not view.settings().get("translate_tabs_to_spaces", False)

        return ClientConfig(
            name='lsp-vue',
            binary_args=[
                'node',
                server_path
            ],
            tcp_port=None,
            enabled=True,
            init_options={
                "config": config
            },
            settings=dict(),
            env=dict(),
            languages=[
                LanguageConfig(
                    'vue',
                    ['text.html.vue'],
                    ["Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"]
                )
            ]
        )
```

**Comment by predragnikolic** [comment]
This issue is fixed. Tab size is read from the user preferences.
If someone finds a nicer way to do this, PR are welcome.

I will open up a new issue for the `Unhandled method workspace/executeCommand`.
