### ISSUE TITLE
Code action throwing `Unhandled method workspace/executeCommand`

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP-vue#4]
related https://github.com/sublimelsp/LSP-vue/issues/3#issuecomment-524610836

> <img width="794" alt="Screen Shot 2019-08-25 at 10 11 01 AM" src="https://user-images.githubusercontent.com/22029477/63647421-6f7fb780-c721-11e9-85fb-e7436f53130d.png">
>
> But when I chose a code action, I now get `Unhandled method workspace/executeCommand`.
> <img width="308" alt="Screen Shot 2019-08-25 at 10 10 51 AM" src="https://user-images.githubusercontent.com/22029477/63647425-81f9f100-c721-11e9-93ae-5ab9a502dc0e.png">
>
> The import statement is not inserted at the top, because of that error.

**Comment by rchl** [comment]
Checked VSCode. It gets those code actions but somehow only shows the second one (and also that fix is not working properly but that's vetur issue).
```
[Trace - 10:31:06 PM] Received response 'textDocument/codeAction - (43)' in 115ms.
Result: [
    {
        "title": "Ignore this error message",
        "command": "vetur.applyWorkspaceEdits",
        "arguments": [
            {
                "changes": {
                    "file:///Users/rchlodnicki/workspace/tidal-account/app/pages/profile/index.vue": [
                        {
                            "newText": "// @ts-ignore\n",
                            "range": {
                                "start": {
                                    "line": 63,
                                    "character": 0
                                },
                                "end": {
                                    "line": 63,
                                    "character": 0
                                }
                            }
                        }
                    ]
                }
            }
        ]
    },
    {
        "title": "Disable checking for this file",
        "command": "vetur.applyWorkspaceEdits",
        "arguments": [
            {
                "changes": {
                    "file:///Users/rchlodnicki/workspace/tidal-account/app/pages/profile/index.vue": [
                        {
                            "newText": "// @ts-nocheck\n",
                            "range": {
                                "start": {
                                    "line": 0,
                                    "character": 0
                                },
                                "end": {
                                    "line": 0,
                                    "character": 0
                                }
                            }
                        }
                    ]
                }
            }
        ]
    }
]
```

**Comment by Narretz** [comment]
I noticed this problem, and I think I found the reason.
Vetur doesn't implement workspace/executeCommands, but instead handles the codeAction fixes in the client and hooks into vscode directly:
https://github.com/vuejs/vetur/blob/139bc1b0e11acd0eef3212012bbd624e6a3ab73b/client/vueMain.ts#L41-L45

A codeFix returned by Vetur looks like this:
```
title: Remove unused declaration for: 'data'
command: vetur.applyWorkspaceEdits
edit: None 
```
(it has an arguments prop instead)

LSP then thinks this is a server command and sends it to vetur which replies with "can't support".
(Imo the error message from LSP could be better)

Not quite sure what to make of this. Seems like vetur should return a normal text edit instead or support vetur.applyWorkspaceEdits on the server.

I confirmed that this works:
```
function createApplyCodeActionCommand(title, uriTextEditMapping) {
    return {
        title,
        command: false,
        edit: {
            changes: uriTextEditMapping
        }
    };
}
```

**Comment by rchl** [comment]
Nice investigation.
Not sure why it can't just handle those as normal code actions...

**Comment by Narretz** [comment]
The option to return "edit" was added in LSP spec version 3.8.0 in June 2018, so maybe vetur simply didn't update their code. (However, the implementation is still wrong, since they don't support workspace/executeCommands.)

**Comment by rchl** [comment]
Should work in next vls version (https://github.com/vuejs/vetur/pull/1704)

**Comment by predragnikolic** [comment]
I can still get `Unhandled method workspace/executeCommand` with vls-0.4.0 :)

**Comment by rchl** [comment]
Right. So the `vetur.applyWorkspaceEdits` command was fixed but there is still `vetur.chooseTypeScriptRefactoring` that is partially implemented in the vetur extension (it seems weird as the extension seems to just be forwarding the request and applying edits which shouldn't be needed there - https://github.com/vuejs/vetur/blob/7a513c43e771bf84fedf406908d1f3022031c672/client/vueMain.ts#L42-L48)

**Comment by predragnikolic** [comment]
I no longer get "Unhandled method workspace/executeCommand"... closing this :)

although when I try to import somthing from a module, that line is put on top of the file, which is a LS bug...
```vue
import { NOTIFICATION_PERMISSION } from '@/services/utils'
<template>
    <aside id="sidebar" class="flex direction-column">
        ...
    </aside>
</template>

<script>
NOTIFICATION_PERMISSION
// i chose code action "import 'NOTIFICATION_PERMISSION' from '@/services/utils' "
</script>

```
