### ISSUE TITLE
version 0.60 crashes on init

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-vue#5]
Version 0.60 of vue-language-server does not work with LSP-vue.

The problem is that when `globalSnippetDir` option is not provided then server crashes. That was fixed in later (unreleased as of now) version but let's assume that it wasn't. To provide that option, I would need to define `globalSnippetDir` key at the same level where `config` is currently, so:
```js
{
        "globalSnippetDir": "/Users/me/snippetsDir",  // <-- HERE
	"config": {
		"vetur": { /* ... */ }
	}
}
```

That doesn't work as LSP-vue only takes the `config` object from configuration file. So I can't fix that problem manually.

Even assuming that the problem is fixed, user should still be able to customize that path.

**Comment by predragnikolic** [comment]
Could you make a PR for this?

I was planning to move the whole client configuration in the sublime settings file.

**Comment by rchl** [comment]
You mean to move it to main sublime settings? Or main LSP settings?

I can make PR but I need to understand what you mean exactly. :)

But I'm not even sure how that move would work because I think we need to ship this package with some configuration defaults (as we do now) that would need to be overridable. And then how would you open tabs with setting showing both default and user's.

Anyways, maybe I can just make PR with handling that specific problem and leave move to some other PR as it seems separate and more complicated

**Comment by predragnikolic** [comment]
If you can, just fix this specific problem.
Thank you :-) 

I meant LSP-vue sublime settings file. But leave that part to me.
