### ISSUE TITLE
Update vue-language-server

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-vue#7]
This package doesn't seem to handle updating the vue-language-server dependency, as far as I can see. Version can be updated in `package.json` but existing users won't get new version. Only way is to remove and re-add the package, I believe.

**Comment by predragnikolic** [comment]
The way I imagined to update the vue-language-server dependency is that I bump up the vls version here https://github.com/sublimelsp/LSP-vue/blob/804dfe33c88c1efe2fbcd0c4f24561855b28eb8d/package.json#L20

And make a new release to package control, 
That would delete the old plugin, and reinstall the dependencies. 

The downside of that is that I have to manually keep track and make a release to package control  each time vls makes a release. 

What do you think, do you have a better suggestion?

**Comment by predragnikolic** [comment]
I bumped the version up, f6cda6736c2d126677d4465b8f322e6f66bb63df
I will do a release now

**Comment by predragnikolic** [comment]
The release will wait, I think Package control is down :)

**Comment by predragnikolic** [comment]
There is a new version of LSP-vue on package control with the newest release of vls.

I also set up `dependabot` for all sublimelsp repositories. 
So each time a dependency updates a PR will automatically be created :) 
like for example https://github.com/sublimelsp/LSP-intelephense/pull/1

Feel free to reopen this issue if you encounter some problems.

**Comment by rchl** [comment]
Seems to have updated for me correctly (vue-language-server dependency was re-installed). Thanks.
