### ISSUE TITLE
Cant disable vetur.colorDecorators

### ISSUE THREAD

**Issue by faaizajaz** [sublimelsp/LSP-vue#82]
I am trying to figure out how to change the setting that adds color phantoms to hex colors (in CSS for example).  See the picture below:

![Screenshot from 2020-10-24 11-04-53](https://user-images.githubusercontent.com/8207214/97069301-c95f6400-15e8-11eb-80f5-1b03f760a32e.png)

According to [this](https://github.com/vuejs/vetur/pull/396) PR, this is controlled by the `vetur.colorDecorators.enable` setting, however adding `"vetur.colorDecorators.enable": false` to the `LSP-vue` settings does not work as expeted.

**Comment by predragnikolic** [comment]
At the time of that PR, the `vetur.colorDecorators.enable` setting was added:
https://github.com/vuejs/vetur/pull/396/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R128

But I presume at some time in later it was removed as I no longer see `vetur.colorDecorators.enable` in the `package.json` file:
https://github.com/vuejs/vetur/blob/master/package.json#L183

___

Instead what you can do is in `LSP.sublime-settings` set `disabled_capabilities`:
```jsonc
{
   // ...other lsp settings
   "disabled_capabilities": ["colorProvider"],
}
```

**Comment by predragnikolic** [comment]
Note: You can install `LSP-json` from package control as it will give you intelligent completions instide LSP.sublime-settings and other Sublime Text plugins that have a [sublime-package.json](https://github.com/sublimelsp/LSP-json#schemas-contributed-by-packages)

**Comment by predragnikolic** [comment]
Feel free to reopen it if you still have problems. :)

**Comment by rchl** [comment]
vetur uses https://github.com/vscode-langservers/vscode-css-languageserver behind the scenes and I can't see it supporting any configuration setting for that. So disabling the capability globally seems like the only way currently.

**Comment by faaizajaz** [comment]
> Instead what you can do is in `LSP.sublime-settings` set `disabled_capabilities`

@predragnikolic disabling `colorProvider` did the trick. Learned some useful stuff in the process, thanks.

**Comment by rwols** [comment]
Note that that disables **all** colorProviders. In particular your css language servers.

**Comment by rchl** [comment]
But if you don't like to have it in vue files then likely you don't want it anywhere. :)

But it would probably be a good idea to support disabling capabilities per-server.

**Comment by faaizajaz** [comment]
I use the ColorHighlighter package so disabling all colorProviders works for me in this case, but I agree on per-server config being useful.
